### ISSUE TITLE
Sponsorship section

### ISSUE THREAD

**Issue by JamsheedMistri** [LosAltosHacks/losaltoshacks.com-2019#3]
We need a finished sponsorship section. Whether it be the horizontal scrolling that @sidd0103 wanted, or just regular (which I think is better), we need to finish it ASAP.

**Comment by Stereopoly** [comment]
@sidd0103 Unless you really want to do the scrolling thing, which a lot of users really dislike when websites take over scrolling, I can go ahead with the static style

**Comment by JamsheedMistri** [comment]
@Stereopoly Perhaps make a branch called `static-sponsor-scrolling` and implement it there. Sidd can do his own thing if he wants on a separate branch.

**Comment by JamsheedMistri** [comment]
Should be very similar to our last year site:
- Partners first, then sponsors
- For partners, 2 per line
- Then we have the major sponsors, which are also 2 per line
- Then everyone else, 3 per line

**Comment by Stereopoly** [comment]
Merged into master, just need to add section headers
